### ISSUE TITLE
Startool incompatible with StarCraft Best Seller Series edition

### ISSUE THREAD

**Issue by timfel** [Wargus/stargus#13]
Hi,

Startool seems to be incompatible with StarCraft Best Seller Series Edition:

samuel@portable:~/starcraft/stargus-instdir/bin$ ./startool /media/cdrom0/ /home/samuel/starcraft/data.sg
Extract from "/media/cdrom0/" to "/home/samuel/starcraft/data.sg"
Using mpq list file "/home/samuel/starcraft/data.sg/mpqlist.txt"
Please be patient, the data may take a couple of minutes to extract...
Archive "/media/cdrom0//install.exe"
Can't open /media/cdrom0//install.exe
Could not open archive "/media/cdrom0//install.exe", skipping
Archive "/media/cdrom0//stardat.mpq"
Can't open /media/cdrom0//stardat.mpq
Could not open archive "/media/cdrom0//stardat.mpq", skipping
Fatal error: Cannot extract data

Certainly because files are named differently:

samuel@portable:~$ ls /media/cdrom0
Autorun.inf  Installer.ico  Installer Tome.mpq  StarCraft (Windows).exe

I'm running latest bazaar revisions for both Stratagus and Stargus, on Debian 7.1 64 bits.

Sincerely,

Samuel

---

Imported from Launchpad using lp2gh.
- date created: 2013-07-26T14:59:25Z
- owner: samuel-viscapi
- the launchpad url was https://bugs.launchpad.net/bugs/1205368

**Comment by timfel** [comment]
(by brad-c6)
Try taking the Installer Tome.mpq and coping to the your computer and rename it "install.exe". Then point Startool at that directory

**Comment by timfel** [comment]
(by samuel-viscapi)
Hi,

/media/cdrom0

cp Installer\ Tome.mpq /home/samuel/install.exe

mkdir /home/samuel/starcraft/data.sg

cp /home/samuel/starcraft/stargus/mpqlist.txt /home/samuel/starcraft/data.sg

cd /home/samuel/starcraft/stargus/build

./startool /home/samuel /home/samuel/starcraft/data.sg

samuel@portable:~/starcraft/stargus/build$ ./startool /home/samuel /home/samuel/starcraft/data.sg
Extract from "/home/samuel" to "/home/samuel/starcraft/data.sg"
Using mpq list file "/home/samuel/starcraft/data.sg/mpqlist.txt"
Please be patient, the data may take a couple of minutes to extract...
Archive "/home/samuel/install.exe"
Not found: files\stardat.mpq

Bye, Sam

**Comment by timfel** [comment]
(by brad-c6)
The internal structure of the MPQ is different from that of the US original edition.
It might be if you extract using MPQExtractor(https://github.com/Kanma/MPQExtractor) the file "Common/Starcraft.mpq" and then change it's name to install.exe that might work

**Comment by timfel** [comment]
(by electricprism-m)
After banging my head against the wall I finally was able to generate a data.sg file on Arch Linux.

I first mounted my starcraft backup iso.

###
# Startool usage is as follows

$ startool -h
startool V1.0 for Stratagus (c) 2002-2012 by the Stratagus Project.
  Written by Lutz Sammer, Nehal Mistry, and Jimmy Salmon and Pali Rohar.
  https://launchpad.net/stargus
Usage: startool archive-directory [destination-directory] [mpqlist-file]
	-V	Show version
	-h	Show usage
archive-directory	Directory which include the archive install.exe or stardat.mpq...
destination-directory	Directory where the extracted files are placed.
mpqlist-file	mpqlist.txt file which contains mpq file names

#
###

I had to  manually specify the 3rd hidden option "mpqlist-file" - once I manually linked to this file it was able to build a data.sg file in my home directory.

startool /run/media/electricprism/StarCraft /home/electricprism/data.sg /usr/share/games/stratagus/stargus/mpqlist.txt

Hope this info helps others out there experiencing the same problem.

**Comment by xythobuz** [comment]
Similar problems here. First, I had to `touch ~/.stratagus/sc/data/mpqlist.txt` to get something other than "could not open archive". Now instead I get this error:

    Archive "/Users/thomas/StarCraft//starcraft.mpq"
    Not found: files\font\font8.fnt

The archive exists, this is my installed Version StarCraft 1.15.2 and it works flawlessly in Windows, although I'm not sure where it's from, exactly...

**Comment by timfel** [comment]
I have seen this problem, might have a temporary fix / workaround soon.

**Comment by timfel** [comment]
@xythobuz you shouldn't have to use an empty mpqlist file, there is one that comes with this project, could you try it? Also, I have updated the windows installer, you could try extracting the data in windows and moving it to your unix box

**Comment by Hypexed** [comment]
What's the result here? I'm trying to help someone else with this edition install but it always breaks. Should this work now?
