### ISSUE TITLE
HD hud

### ISSUE THREAD

**Issue by sheepo99** [Wargus/stargus#16]
It shouldn't be too hard to add some graphical witchcraft to extend the HUD so it looks better in HD resolutions. Look at how this now defunct brood war mod did it:

https://www.youtube.com/watch?v=1C6m98FkLK4

**Comment by timfel** [comment]
It shouldn't be too hard, no. Right now I'm leaning more in the direction of simply not allowing changing the viewport size (so the logical resolution is always as in the original game), and then using scaling filters to make the graphics look nice on larger resolutions. But if somebody were to contribute a HD hud (or graphics to scale it) ... ;)

**Comment by sheepo99** [comment]
For scaling purposes, I think it can be a achieved with a very simple copypasting job on photoshop. This would, however, require splitting of the 3 original HUDs which, once again, might require some wizardry, this time in automated image splitting when extracting the files.

Either way, I'm very glad to know Stargus is still getting attention from the team. I hope 2.40 comes soon, since I've dying to fiddle with the latest versions on windows.
