### ISSUE TITLE
Stargus and Stratgus windows versions to download is not same

### ISSUE THREAD

**Issue by yaaaaa** [Wargus/stargus#17]

**Comment by timfel** [comment]
Indeed, but they do work together. Stargus is still incomplete.

**Comment by yaaaaa** [comment]
I install Stratagus 2.4.0
but Stargus wont install to me

---------------------------
Stargus Setup
---------------------------
Stratagus 2.3.9 is not installed.
You need Stratagus 2.3.9 to run Stargus!
First install Stratagus 2.3.9 from https://github.com/Wargus/stratagus
---------------------------
ОК   
---------------------------

**Comment by timfel** [comment]
I have updated stargus to 2.4.0. This should be gone now.

**Comment by yaaaaa** [comment]
=)
