### ISSUE TITLE
Stargus not starting due to files missing

### ISSUE THREAD

**Issue by baco** [Wargus/stargus#19]
After a correct extraction of files by the startool of the StarCraft CD v1.00 Stargus fails to start.

Running Stargus from command line outputs the following error:

```
fluidsynth: error: Get end of file position failed
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont "/home/xxxx/.stratagus/sc/"
fluidsynth: error: Unable to open file ""
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont ""
Failed to load the SoundFont: 
Can't open file: No such file or directory
Can't load the graphic 'ui/fonts/font10.png'
```

missing ui font font10.png seems to be the problem.

**Comment by timfel** [comment]
Ah, yes, I remember an issue with that. I think our extraction of from
either the CD or the install folder is incomplete and is then missing these
font files. Can you try try extracting from the install folder if you did
it from the CD or vice versa?

Am 18.07.2016 18:34 schrieb "Dionisio E Alonso" <notifications@github.com>:

**Comment by baco** [comment]
I had extracted the data from the CD, or something like that; I had the iso file mounted and tried the extraction from there. At the moment I can not try extracting the data from the install folder because I do not have Windows to install it (although I guess I could try installing it with Wine).

Nevertheless I could extract the data from the mounted iso file using `startool` from version 2.2.0 of Stargus and then upgrading again to version 2.4.0 the package. That extraction had the font files and Stargus launched correctly.

**Comment by eldambro** [comment]
I have the same issue... I'm looking on internet the 2.2.0 version of stargus but without success... can you tell me please where can I find it and the steps for make Stratagus work? thanks a lot!

**Comment by Shalkith** [comment]
Still getting this error. Tried both options. Even tried merging both directories into one.

Is there a fix?

**Comment by timfel** [comment]
@eldambro If anything, you're most likely to have luck with the current nightly https://github.com/Wargus/stargus/releases

**Comment by timfel** [comment]
@baco the 2.4.0 version is old, and for stargus there isn't really anything stable, I'd recommend you try with a nightly build, best chance there
