### ISSUE TITLE
[Starting] stargus cant start on RPI 3

### ISSUE THREAD

**Issue by Ted-bissada** [Wargus/stargus#20]
When i try and start stargus or stratagus binaries normally nothing happens 
When i try and start stargus or stargus from command line i get 

```
[string "/usr/local/share/games/stratagus/stargus/sc..."]:86: attempt to call global 'SetMetaServer' (a nil value)
stack traceback:
              ["/usr/local/share/games/stratagus/stargus/sc..."]:86: in main chunk
```

**Comment by timfel** [comment]
This bug should be fixed in the 2.4.1 release. Stargus is running for example with RetroPie.
