### ISSUE TITLE
[Installer] Allow an installed StarCraft:BW as Source

### ISSUE THREAD

**Issue by yaaaaa** [Wargus/stargus#22]
Use the already installed "StarCraft:BW" as Source for Content Installation.

**Comment by timfel** [comment]
This should work, this is the setup I am using. What error messages (if any) do you see, and what is your OS?

**Comment by yaaaaa** [comment]
My Os is Windows 10 x64, install progress do not display any errors, but game du not start (after install I must download preinstalled content and replace mine, then game is starts normally)

**Comment by yaaaaa** [comment]
tested 2.4.1 release, instalation progress with copy content from from preinstalled BW is sucesfully and geme is work (maybe I used another/wrong version of BW when I testd earlier version of stratagus)
