### ISSUE TITLE
When I use OpenGL video, the game is crash

### ISSUE THREAD

**Issue by yaaaaa** [Wargus/stargus#25]
When I use OpenGL video, game crash at loading map, or crash at click to build probe

If you need any files, logs and info, I can put it here

**Comment by timfel** [comment]
Yes, I have noticed that, but I don't have time to investigate those crashes.

**Comment by timfel** [comment]
With the latest 2.4.1 release, this is now working for me. What OS are you on?

**Comment by yaaaaa** [comment]
tested 2.4.1 release, crashes at click to build probe and at load is gone, but if i use diablo map, the game is stend on tileset png loading

**Comment by timfel** [comment]
yes, that tileset has not been enabled, yet.
