### ISSUE TITLE
StarCraft 1.18

### ISSUE THREAD

**Issue by johndoe71rus** [Wargus/stargus#31]
Hi.
How to use files downloaded by StarCraft-Setup.exe, latest 1.18 patch?
Is this correct that now we can free use that resources?

**Comment by johndh** [comment]
I hope so!  To test, I downloaded it from Blizzard's site, ran the installer in Wine, which seemed to go smoothly, then ran Stargus and pointed it at Starcraft.mpq.  After the extraction process, here's the result:

```
Can't open file 'preferences.lua': No such file or directory
Stratagus v2.4.1, Copyright (c) 1998-2015 by The Stratagus Project
  written by Lutz Sammer, Fabrice Rossi, Vladi Shabanski, Patrice Fortier,
  Jon Gabrielson, Andreas Arens, Nehal Mistry, Jimmy Salmon, Pali Rohar,
  cybermind and others.
	https://github.com/Wargus/stratagus
Compile options ZLIB BZ2LIB VORBIS THEORA FLUIDSYNTH MIKMOD MNG OPENGL LINUX X11 

Stratagus may be copied only under the terms of the GNU General Public License
which may be found in the Stratagus source kit.

DISCLAIMER:
This software is provided as-is.  The author(s) can not be held liable for any
damage that might arise from the use of this software.
Use it at your own risk.

fluidsynth: error: Get end of file position failed
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont "/home/user/.stratagus/sc/"
fluidsynth: error: Unable to open file ""
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont ""
Failed to load the SoundFont: 
Can't open file: No such file or directory
Can't load the graphic 'ui/fonts/font10.png'
```

No joy yet, but I'm hoping somebody can get this working.

**Comment by johndoe71rus** [comment]
i do the same, and get the same. I think i made some wrong.

**Comment by timfel** [comment]
I'm not sure what you downloaded, but the extraction only works with the CD or the installation folder for the full version. I tried with the version downloaded by the battle.net installer, that works.

**Comment by johndh** [comment]
@timfel For me, I downloaded the Starcraft Anthology from https://us.battle.net/account/download#classic

This comes as an installer, StarCraft-Setup.exe, which (via Wine) installs the following:
```
user@box ~/.wine/drive_c/Program Files (x86)/StarCraft $ ls
BlizzardError.exe            License.html       SEditITA.loc
BrooDat.mpq                  License.txt        SEditPTB.loc
BroodWar.mpq                 Local.dll          StarCraft.exe
cef                          Maps               StarCraft Launcher.exe
ClientSdk.dll                patch_rt.mpq       StarCraft Manual.pdf
ClientSdkFirewallHelper.exe  Release Notes.txt  Starcraft.mpq
ClientSdkMDNSHost.exe        Riched20.dll       StarDat.mpq
data                         SEditDEU.loc       StarEdit.exe
Data                         SEditENU.loc       StarEditHelp
EditLocal.dll                SEditESP.loc       storm.dll
Launcher.db                  SEditFRA.loc       SystemSurvey.exe

```

Running Stargus, and pointing it at Starcraft.mpq creates a directory, ~/.stratagus/data.Stargus which contains folders `graphics`, `scripts`, and `sounds`, text files `extracted`, and `mpqlist.txt`

[mpqlist.txt](https://github.com/Wargus/stargus/files/995319/mpqlist.txt)


Is this the same installer that worked for you?  If so, what is different on your end?

**Comment by Hypexed** [comment]
Does it download it over the internet? There's about 600MB worth of data it would need to install. And the Startool extracts every known file from the Starcraft.mpq? I can't see what length your files are up there.

**Comment by johndh** [comment]
@Hypexed yes, `StarCraft-Setup.exe` is only 3.2MB and it downloads everything from the internet into a directory in `~/.wine`.  When running `stargus` for the first time, it asks for an input file, and I specify `Starcraft.mpq`.
`~/.wine/drive_c/Program\ Files\ (x86)/StarCraft/` is 3.8GB
`Starcraft.mpq` is 606.9MB
`BroodWar.mpq` is 571.8MB
`BrooDat.mpq` is 21.8MB
`~/.stratagus/data.Stargus/` is 89.9MB

Running `startool` itself apparently does nothing productive.
```
user@box ~/.wine/drive_c/Program Files (x86)/StarCraft $ startool ./Starcraft.mpq 
Extract from "./Starcraft.mpq" to "data"
Using mpq list file "data/mpqlist.txt"
Please be patient, the data may take a couple of minutes to extract...
Archive "./Starcraft.mpq/install.exe"
Can't open ./Starcraft.mpq/install.exe
Could not open archive "./Starcraft.mpq/install.exe", skipping
Archive "./Starcraft.mpq/Install.exe"
Can't open ./Starcraft.mpq/Install.exe
Could not open archive "./Starcraft.mpq/Install.exe", skipping
Archive "./Starcraft.mpq/starcraft.mpq"
Can't open ./Starcraft.mpq/starcraft.mpq
Could not open archive "./Starcraft.mpq/starcraft.mpq", skipping
Archive "./Starcraft.mpq/StarCraft.mpq"
Can't open ./Starcraft.mpq/StarCraft.mpq
Could not open archive "./Starcraft.mpq/StarCraft.mpq", skipping
Archive "./Starcraft.mpq/StarDat.mpq"
Can't open ./Starcraft.mpq/StarDat.mpq
Could not open archive "./Starcraft.mpq/StarDat.mpq", skipping
Archive "./Starcraft.mpq/StarDat.mpq"
Can't open ./Starcraft.mpq/StarDat.mpq
Could not open archive "./Starcraft.mpq/StarDat.mpq", skipping
DONE!
```
Note: this is the same behavior as your issue #26

**Comment by johndh** [comment]
No idea about `preferences.lua`, but running `MPQExtractor` on `Starcraft.mpq` does yield a file called font10, but it's `files/font/font10.fnt`, not `ui/fonts/font10.png`... so did they change file formats between original StarCraft to Brood Wars?  And it's definitely not a png with a weird extension, as I tried changing it to .png and it won't open as an image.  Also, `~/.stratagus/sc` is empty, if that matters.

**Comment by Katana-Steel** [comment]
running startool should point it to a directory not the mpq file, it should pick up both Starcraft.mpq and StartDat.mpq from there...

if you're already in the StarCraft directory you should use **./** as the argument...

startool not only extracts files it also converts them if needed...

**Comment by johndh** [comment]
After fiddling with startool a bit, I figured out the right syntax.  This produced a whole lot more files (graphics and sounds mostly), but data.Stargus still only contains 89.9MB, which is a lot smaller than the 600MB of Starcraft.mpq. and there's still the same end result when launching stargus.

Weirdly enough, I ran a search for some of the files that startool says it extracted, but they're nowhere to be found in the destination directory.  It looks like only graphics and sounds got extracted.

```
user@box ~/.stratagus $ startool '/home/user/.wine/drive_c/Program Files (x86)/StarCraft' /home/user/.stratagus/data.Stargus /home/user/.stratagus/data.Stargus/mpqlist.txt
Extract from "/home/user/.wine/drive_c/Program Files (x86)/StarCraft" to "/home/user/.stratagus/data.Stargus"
Using mpq list file "/home/user/.stratagus/data.Stargus/mpqlist.txt"
Please be patient, the data may take a couple of minutes to extract...
Archive "/home/user/.wine/drive_c/Program Files (x86)/StarCraft/install.exe"
Can't open /home/user/.wine/drive_c/Program Files (x86)/StarCraft/install.exe
Could not open archive "/home/user/.wine/drive_c/Program Files (x86)/StarCraft/install.exe", skipping
Archive "/home/user/.wine/drive_c/Program Files (x86)/StarCraft/Install.exe"
Can't open /home/user/.wine/drive_c/Program Files (x86)/StarCraft/Install.exe
Could not open archive "/home/user/.wine/drive_c/Program Files (x86)/StarCraft/Install.exe", skipping
Archive "/home/user/.wine/drive_c/Program Files (x86)/StarCraft/starcraft.mpq"
Can't open /home/user/.wine/drive_c/Program Files (x86)/StarCraft/starcraft.mpq
Could not open archive "/home/user/.wine/drive_c/Program Files (x86)/StarCraft/starcraft.mpq", skipping
Archive "/home/user/.wine/drive_c/Program Files (x86)/StarCraft/StarCraft.mpq"
Can't open /home/user/.wine/drive_c/Program Files (x86)/StarCraft/StarCraft.mpq
Could not open archive "/home/user/.wine/drive_c/Program Files (x86)/StarCraft/StarCraft.mpq", skipping
Archive "/home/user/.wine/drive_c/Program Files (x86)/StarCraft/StarDat.mpq"
extracted: game\icons.grp (872, 2608 bytes)

There were ~3000 more lines here.  Full log available on request if it's useful for some reason.

extracted: sound\misc\explosm.wav (2026, 65132 bytes)
DONE!
```

```
user@box ~/.stratagus $ stargus > ~/Desktop/starguslogout.txt
Can't open file 'preferences.lua': No such file or directory
fluidsynth: error: Get end of file position failed
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont "/home/user/.stratagus/sc/"
fluidsynth: error: Unable to open file ""
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont ""
Failed to load the SoundFont: 
Can't open file: No such file or directory
Can't load the graphic 'ui/fonts/font10.png'
```

**Comment by Hypexed** [comment]
I forgot about my issue. Yeah the startool won't work then. In fact when I checked the latest Stargus available from a Linux Mint 18 repository at that time it was also broken. I don't know where Tim has gone to but this needs to be fixed. As it stands now Stargus has an official state of broken. I will upload the code fix I wrote to my issue.

But in the mean time try this work around hiding in my issue. Rename your Starcraft.mpq to StarCraft.mpq. Notice the caps there. And run the startool again. But only specify the folder that StarCraft.mpq file is in.

**Comment by timfel** [comment]
@Hypexed is correct, there is a capitalization issue, also, there might be
issues if the folder to starcraft.mpq has spaces in it (or that might have
been in wargus... I forget)

Hypexed <notifications@github.com> schrieb am Sa., 13. Mai 2017, 17:15:

**Comment by johndh** [comment]
Now we're getting somewhere!  So, starting over with a fresh installation, I renamed Starcraft.mpq to StarCraft.mpq, and StarDat.mpq should already be fine. After changing the name, I get a lot more files (up to 545.8MB) and Stargus launches!  I still get the same fluidsynth errors, and the campaign button is grayed out -- is that last one normal?  Does the campaign normally work in Stargus?

I also get a crash that says it can't load certain assets:
```
fluidsynth: error: Get end of file position failed
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont "/home/user/.stratagus/sc/"
fluidsynth: error: Unable to open file ""
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont ""
Failed to load the SoundFont: 
Can't open file 'maps/(2)Space Madness.smp': No such file or directory
Can't find missile missile-zerg-guardian-glaive-wurm
Can't open file: No such file or directory
Can't load the graphic 'tilesets/fog.png'
```
Downloading fog.png and moving it to data.Stargus/tilesets/ makes that part of the error go away, but the other lines remain.  The game launches and is playable for a few seconds.  Some things are still missing (like progress bars) and seg faults abound.  I'll do some further testing.

I'm not sure if the menu is supposed to look like this or not.  I haven't actually played regular StarCraft before (just the demo version, well over a decade ago) but I seem to remember it's got animations and fancier graphics.

![screenshot_2017-05-13_16-14-14](https://cloud.githubusercontent.com/assets/692397/26028908/60fa50e6-37f7-11e7-8bbe-c86247a47ced.png)

**Comment by johndh** [comment]
Attaching the log.
[log_of_stratagus_0.txt](https://github.com/Wargus/stargus/files/998930/log_of_stratagus_0.txt)

**Comment by timfel** [comment]
Campaigns aren't working. Relating to segfaults, yes, there will be many. Only some of the skirmish maps work at all, because most terrains aren't implemented. Unfortunately, both things are a lot of work, and no one seems to have the time to dedicate to it right now. Starcraft is a lot more complex than wargus and war1gus.

Wargus was a multi-year effort by a lot of different people, war1gus took me a few years of a few hours per month even given that most features from wargus could be re-used for war1gus. Stargus would need more changes in the engine. To be honest, it may be easier to start from scratch (at least, it would be more fun, which is an important motivating factor in FOSS game engine projects)

**Comment by johndh** [comment]
@timfel I see.  Thanks for clearing that up.  I'm seeing a LOT of errors, and it's hard to know what might be due to a faulty installation, and what is just "normal" for stargus.  The Terrans are mostly playable, and the Zerg aside from anything creep-related, but the Protoss don't perform as expected at all.

https://www.youtube.com/watch?v=vO4DxWZhqvc

If this is par for the course, then I think this issue is pretty well solved.

**Comment by timfel** [comment]
Yes, Protoss are little more than stubs. Most of that could actually be fixed in pure lua, without having to touch the engine. Zerg creep is on a branch that i never had time to continue, but I also think it could be fixed in pure lua. Same goes for at least basic terrain support for the other map types. Many special abilities like Terran flying buildings can also be done in lua. Given maybe half a year of after work focus by one or two people, skirmish battles could become well playable (although not exactly like the original)

But lots of the mechanics required for the campaign would require changes to the engine.

**Comment by johndh** [comment]
Good to know.  I was initially under the impression (purely from my own imagination, I guess) that Stargus and Wargus were roughly on the same level, and that it was mostly a difference of data -- i.e. StarCraft being as much a total conversion mod as a separate game from WC2.  Now I know that's not the case.

Since StarCraft is now free to download, I would imagine that this will be a significant use case for Stargus, so is there any documentation that needs to be updated with instructions for how to use the downloaded version?  `http://stargus.stratagus.com/install/index.html` perhaps?

**Comment by timfel** [comment]
Unfortunately, I don't know who has access to that domain and server. The current website we're using is http://wargus.github.io. @mimooh did a lot of work on that website, I think we can add Stargus to the list of games and put instructions there.

**Comment by Hypexed** [comment]
Also to add, yes it's normal for the start screen to look like that, since it's not an exact close but recreation. Even if it uses the same in game graphics and sounds.

Regarding the segfaults, I thought this was solved a while ago. Or, at least, solved in Stratagus. But it looks like it is not. I compiled and packaged an earlier Stargus, IIRC 2.2.4 build, for the AmigaOS4 PowerPC platform. And in testing I got a huge amount of crashes. Most of the time these were basic NULL pointer reads, things that shouldn't be in release versions, even if Stratagus on the whole is an ongoing project. This gave me the impression that Stratagus was poorly coded because it threw around a lot of pointers to functions without checking if was a valid pointer. It just looked bad! :-)

I spent some time "hacking" the code to check first which tamed them down but still left me wondering why the code kept assuming the pointers existed. In the end I simply used an assert  to catch any other I missed.

**Comment by johndh** [comment]
Alright, here are my proposed instructions, if anyone has access and wants to list them somewhere:

> StarCraft is now (as of 2017) free to download from Blizzard, so the installation CD is no longer required for Stargus.
> 
> Download the Starcraft Anthology installer from:
> https://us.battle.net/account/download#classic
> and run it (using Wine if on Linux or Mac)
> 
> Locate the installed files and rename Starcraft.mpq to StarCraft.mpq so that Stargus knows to use it.
> 
> Launch Stargus.  When prompted, point it toward the newly-renamed StarCraft.mpq.  Stargus will extract the necessary files from StarCraft.mpq and StarDat.mpq (into ~/.stratagus/data.Stargus/ on Linux)
> 
> Move fog.png to ~/.stratagus/data.Stargus/graphics/tilesets/
> 
> You no longer need the StarCraft installation, and may delete it at your discretion.

@Hypexed the Wyrmgus engine has been seeing a lot of development and has squashed a lot of seg faults.  Might be worth checking out the changes there if you're not already familiar.

@johndoe71rus can you try these instructions and see if it works for you?

**Comment by johndoe71rus** [comment]
http://paste.ubuntu.com/24588240/ 
mostly break. One time was black screen with log line bottom and terran music. break by ctrl+z

**Comment by johndh** [comment]
@johndoe71rus `Can't load the graphic 'tilesets/fog.png'` -- do you have a copy of fog.png in `data.Stargus/graphics/tilesets`?  It doesn't get installed by default, so you have it put it there manually, either by finding wherever Stargus installed it, or by downloading it from the repo.
https://github.com/Wargus/stargus/blob/master/contrib/fog.png

I think some maps don't work at all either.  Try the map "Holy Ground" and see if it loads, as that one works for me.

**Comment by Hypexed** [comment]
@johndh I haven't seen Wyrmgus but looked up the project last night.

@johndoe71rus This error you got: `Can't open file 'maps/(2)Challenger.smp': No such file or directory`
Is what I used to get a lot. IIRC the file was there but would need to check.

@all What I usually do is play a game with default settings and it tends to work well. Well enough. Unless the game get complicated and beyond what Stargus has to offer.

**Comment by johndoe71rus** [comment]
yes, copy fog.png but wrong folder.
Now start 
https://s7.postimg.org/5ph5hocsr/2017-05-17-181627_1280x800_scrot.png
then 
https://s24.postimg.org/fstqxzyt1/2017-05-17-182005_1280x800_scrot.png
and error with memory dump
http://paste.ubuntu.com/24593242/

think then alien base died.
