### ISSUE TITLE
Error to extract StarDat.mpq

### ISSUE THREAD

**Issue by fripSide** [Wargus/stargus#42]
...
Archive "archive-directory/StarCraft Archive"
Can't open archive-directory/StarCraft Archive
Could not open archive "archive-directory/StarCraft Archive", skipping

(null):
Fatal error: Cannot extract data

Problem is herer, There is an empty line config.
https://github.com/Wargus/stargus/blob/master/startool.cpp#L245

**Comment by Hypexed** [comment]
That was me. I put in the blank config as the scanner was too rigid and hard to expand for new lines. I recall it was to terminate the list. But it shouldn't break unless it can't understand the file format. It looks like like it got to the end and stopped.
