### ISSUE TITLE
Can not extract Starcraft.mpq from battle.net digital version

### ISSUE THREAD

**Issue by legluondunet** [Wargus/stargus#44]
Hello,
is stargus compatible with last Starcraft.mpq/stardat.mpq from battle.net digital version?
When I try to use mine, I obtained only this errors messages:

![Capture d’écran de 2020-04-25 19-33-37](https://user-images.githubusercontent.com/325405/80286457-d5e32c80-872b-11ea-9310-a5e9859b36ff.png)

![Capture d’écran de 2020-04-25 19-33-49](https://user-images.githubusercontent.com/325405/80286454-d4b1ff80-872b-11ea-9575-fe38cca95c69.png)

![Capture d’écran de 2020-04-25 19-33-45](https://user-images.githubusercontent.com/325405/80286455-d54a9600-872b-11ea-8ae9-3f8ce6f15f52.png)

**Comment by spiderman82** [comment]
same problem!
