### ISSUE TITLE
Build failed on Linux documentation needed for dependancies)

### ISSUE THREAD

**Issue by coreybruce** [Wargus/stargus#48]
hey there, I was trying to build this but ran into a issue, also documentation on how to build is missing, What dependencies are needed to compile this?

```
 cmake -DSTRATAGUS=stratagus -DSTRATAGUS_INCLUDE_DIR=${PATH_TO_STRATAGUS_SRC}/gameheaders ../
make
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:30 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/libpng.so (found version "1.6.37") 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found Freetype: /usr/lib/libfreetype.so (found version "2.11.1") 
CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (GTK2_GTK)
  does not match the name of the calling package (GTK2).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindGTK2.cmake:532 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:98 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found GTK2_GTK: /usr/lib/libgtk-x11-2.0.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/Storage/Project/stargus/build
[  9%] Building CXX object CMakeFiles/scmconvert.dir/mpq.cpp.o
[ 18%] Building CXX object CMakeFiles/scmconvert.dir/scm.cpp.o
[ 27%] Building CXX object CMakeFiles/scmconvert.dir/huff.cpp.o
[ 36%] Linking CXX executable scmconvert
[ 36%] Built target scmconvert
[ 45%] Building CXX object CMakeFiles/stargus.dir/stargus.cpp.o
/mnt/Storage/Project/stargus/stargus.cpp:38:10: fatal error: stratagus-game-launcher.h: No such file or directory
   38 | #include "stratagus-game-launcher.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/stargus.dir/build.make:76: CMakeFiles/stargus.dir/stargus.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/stargus.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by timfel** [comment]
Hi, you can check travis.yml, you need stratagus to build stargus. https://github.com/Wargus/stargus/blob/c8510a8156a31282978bcbec6d99874611e83734/.travis.yml#L18

However, stargus is unmaintained, it won't work with the latest Stratagus. Some people were interested in reviving it, but the master of stargus is 3 Stratagus versions old

**Comment by coreybruce** [comment]
> Hi, you can check travis.yml, you need stratagus to build stargus.
> 
> https://github.com/Wargus/stargus/blob/c8510a8156a31282978bcbec6d99874611e83734/.travis.yml#L18
> 
> However, stargus is unmaintained, it won't work with the latest Stratagus. Some people were interested in reviving it, but the master of stargus is 3 Stratagus versions old

Oh I see so there is a bit of a maintenance issue here on their end to make this work properly?

**Comment by timfel** [comment]
> Oh I see so there is a bit of a maintenance issue here on their end to make this work properly?

well, there was just no one interested in making Stargus work in the kast 6 or 7 years, so no one did

**Comment by coreybruce** [comment]
I think you should combine it with this project and update it so you don't have to rely on a seperate project that may or may not be maintained while making it easier for you and other user to compile/maintain if possible

**Comment by Kintobor** [comment]
There is interest in working on Stratagus, but none for Stargus.

Using an old version of Stratagus is probably the only option until someone starts working on Stargus again.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by timfel** [comment]
> I think you should combine it with this project and update it so you don't have to rely on a seperate project that may or may not be maintained while making it easier for you and other user to compile/maintain if possible

If anyone wants to work on Stargus, they can very easily. Until then, @Kintobor is exactly right, no one wants to work on it and it will remain broken. You can use the last release with the appropriate Stratagus version (2.4.1).
